### ISSUE TITLE
Example doesn't compile

### ISSUE THREAD

**Issue by redDwarf03** [WalletConnect/Web3ModalFlutter#10]
Thank you for this lib.
When i try to clone the project, I have some issues in the example project:

- `Web3ModalTheme` and `Web3ModalConnect` don't exist in the project
- import are not ok. We should have`import 'package:web3modal_flutter/walletconnect_modal_flutter.dart';` instead of `import 'package:web3modal_flutter/web3modal_flutter.dart';`

**Comment by Luzzotica** [comment]
This library is deprecated in favor of the WalletConnectModal (For now).

Once the WalletConnectModal is up to snuff, I will begin my work on this library.
