### ISSUE TITLE
How to support TRON support how to do this ?

### ISSUE THREAD

**Issue by AnitaGVMTechnologies** [WalletConnect/Web3ModalFlutter#101]
<img width="244" alt="Screenshot 2024-03-19 at 3 49 42 PM" src="https://github.com/WalletConnect/Web3ModalFlutter/assets/133353238/f5e80319-e3d7-4032-8f4a-77728672bb06">

![image](https://github.com/WalletConnect/Web3ModalFlutter/assets/133353238/e0ba2ad1-2865-4ef8-8e58-a8f836d40f2c)

I need this into Android device support !!

**Comment by quetool** [comment]
Hello @AnitaGVMTechnologies, TRON network is not yet supported!
