### ISSUE TITLE
Getting invalid argument error for parameters field when using requireWriteContract

### ISSUE THREAD

**Issue by arrayappy** [WalletConnect/Web3ModalFlutter#113]
**Describe the bug**
We are working on a flutter app and working with WalletConnect. We are facing issue calling write contracts. I’m trying to call this payable smart contract function, but It is not working.
```Error: Invalid argument (params): Must match function parameters: 3```
I tried with 1 parameter and 3 parameters as well. Facing the same issue.
When I verify even in abi, it only takes on parameter with uint256 type.

**Additional context**
![telegram-cloud-photo-size-5-6134025911251616955-y](https://github.com/WalletConnect/Web3ModalFlutter/assets/46554685/ad7972bb-bfcf-4229-9dfd-d7b298cbabd8)

**Comment by quetool** [comment]
Hello @arrayappy, without any more context I can't help. Can you share the ABI file and contract address by any chance? Or at least the `joinPublicChallenge` function declaration?

**Comment by quetool** [comment]
Hello @arrayappy, I saw you closed the issue. Is it solved? Let me know if you need any more help.

**Comment by arrayappy** [comment]
Parameters issue was resolved, later faced issue with not redirecting to Metamask. Used this [below logic](https://github.com/WalletConnect/WalletConnectFlutterV2/issues/246#issuecomment-1905591958) to make it work.
