### ISSUE TITLE
Wallet buttons keeps on loading forever. Getting 'Forbidden' error in terminal.

### ISSUE THREAD

**Issue by Trilochan20** [WalletConnect/Web3ModalFlutter#114]
**Describe the bug**
The buttons don't load and loading shows and continues for infinity

here is my code

```
import 'package:flutter/material.dart';
import 'package:web3modal_flutter/web3modal_flutter.dart';

class WalletLoginSystem extends StatefulWidget {
  const WalletLoginSystem({super.key});

  @override
  State<WalletLoginSystem> createState() => _WalletLoginSystemState();
}

class _WalletLoginSystemState extends State<WalletLoginSystem> {
  late W3MService _w3mService;

  @override
  void initState() {
    super.initState();

    _initializeW3MService();
  }

  void _initializeW3MService() async {
    _w3mService = W3MService(
      projectId: '4a1542d08d8546a5b43d0138bbd6c436',
      metadata: const PairingMetadata(
        name: 'CirclesApp',
        description: 'Web3Modal Flutter Example',
        url: 'https://www.web3modal.com/',
        icons: ['https://web3modal.com//images/rpc-illustration.png'],
        redirect: Redirect(
          native: 'flutterdapp://',
          universal: 'https://www.web3modal.com',
        ),
      ),
    );

    await _w3mService.init();
  }

  @override
  Widget build(BuildContext context) {
    return SafeArea(
        child: Scaffold(
      appBar: AppBar(
        title: const Text('Wallet Login'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            W3MConnectWalletButton(service: _w3mService),
            const SizedBox(height: 16),
            W3MNetworkSelectButton(service: _w3mService),
            const SizedBox(height: 16),
            W3MAccountButton(service: _w3mService)
          ],
        ),
      ),
    ));
  }
}

```

**Screenshots**
<img width="1091" alt="Screenshot 2024-04-21 at 1 00 25 AM" src="https://github.com/WalletConnect/Web3ModalFlutter/assets/29045013/17655d92-e268-46d6-bb59-bd24181937b2">
![Screenshot 2024-04-21 at 1 00 38 AM](https://github.com/WalletConnect/Web3ModalFlutter/assets/29045013/804137d5-a607-4aab-84f6-6df1dcfb67e3)
<img width="618" alt="Screenshot 2024-04-21 at 1 01 03 AM" src="https://github.com/WalletConnect/Web3ModalFlutter/assets/29045013/85e35454-8775-4fd9-886e-45febd757f25">

**Smartphone (please complete the following information):**
- Android 14, emulator
- Flutter latest SDK

**Additional context**
Am I missing something here ?

**Comment by anhnh-yoong** [comment]
Same issue

**Comment by anhnh-yoong** [comment]
@quetoo Can you help us. I make sure I set the right projectId. Thank you

**Comment by Cali93** [comment]
Hey @Trilochan20 and @anhnh-yoong,

Thanks for reporting the issue and your patience.
There was a bug on our Web3Modal API where all project IDs created from April 18 until today were considered invalid.
The issue has been resolved and the requests should now get a valid response.

Sorry for the inconvenience.
