### ISSUE TITLE
[ExplorerService] Error fetching native apps data

### ISSUE THREAD

**Issue by kishanflutter** [WalletConnect/Web3ModalFlutter#115]
I[ExplorerService] init()
 [ExplorerService] Error fetching native apps data
 [ExplorerService] Error fetching native apps data
Exception: FormatException: Unexpected character (at character 1)
 Bad Request

**Comment by quetool** [comment]
Hello @kishanflutter @LorenzoPorrega, it should be solved already, please let us know!
https://status.walletconnect.com/incidents/btx0p36pywqd
