### ISSUE TITLE
[Bug]Metamask signature does not work.

### ISSUE THREAD

**Issue by iseruuuuu** [WalletConnect/Web3ModalFlutter#122]
**Describe the bug**
- After the metamask is logged in, the signature process is called, but not only is the metamask not opened, but the signature process is not called.

**To Reproduce**
1. Launch metamask and connect
2. Go back to the app and "sign wallet
3. launch metamask and sign
4. go back to the app and log in

**Expected behavior**
Transition to the meta mask and expect to be able to process signatures

**Screenshots**
- I want to send a video, but skip it because it contains meta mask information.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 7 
 - OS: 14

**Flutter Doctor**

```shell
[✓] Flutter (Channel stable, 3.16.5, on macOS 14.4.1 23E224 darwin-arm64 (Rosetta), locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.88.0)
```

**Additional context**
- Specific implementations are described
- For Packages, only those necessary to explain

```yaml 
dependencies:
  web3modal_flutter: ^3.1.3
  riverpod_annotation: ^2.3.3
  
dev_dependencies:
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
```

```dart
import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:web3modal_flutter/web3modal_flutter.dart';

part 'wallet_connect.g.dart';

@riverpod
Future<W3MService> walletConnect(WalletConnectRef ref) async {
  const metamask =
      'c57ca95b47569778a828d19178114f4db188b89b763c899ba0be274e97267d96';
  final w3mService = W3MService(
    projectId: ApiConstants.projectId,
    includedWalletIds: {metamask},
    featuredWalletIds: {metamask},
    excludedWalletIds: {metamask},
    metadata: const PairingMetadata(
      name: 'Web3Modal Flutter Example',
      description: 'Web3Modal Flutter Example',
      url: 'https://web3modal.com/',
      icons: ['https://web3modal.com/images/rpc-illustration.png'],
      redirect: Redirect(
        native: 'web3modalflutter://',
        universal: 'https://web3modal.com',
      ),
    ),
  );
  await w3mService.init();
  return w3mService;
}

```

```dart
/// Provider for signature
@riverpod
class Certification extends _$Certification {
  @override
  bool build() {
    return false;
  }

 Future<bool> certificationWithWalletConnect(BuildContext context) async {
    final walletConnect = await ref.read(walletConnectProvider.future);
    ///  The address is ready to be acquired.
    final address = ref.watch(walletProvider);
    /// The nonce is also getting it right.
    final nonce = await getNonce();
    final bytes = utf8.encode('Here is a basic message!$nonce');
    final encoded = hex.encode(bytes);
　///  I want to call in signedMessage, but the signature process doesn't work.
    final signedMessage = await walletConnect.web3App!.request(
      chainId: 'eip155:1',
      topic: walletConnect.session?.topic ?? '',
      request: SessionRequestParams(
        method: 'personal_sign',
        params: ['0x$encoded', address],
      ),
    );

    if (signedMessage == '') {
      return false;
    }
    return true;
  }

```

**Comment by iseruuuuu** [comment]
# Referenced implementations
- https://docs.walletconnect.com/web3modal/flutter/actions#send-an-rpc-request

**Comment by iseruuuuu** [comment]
# Status quo
1. Attempt login with `walletConnect.openModal(context);` to open meta-mask → login succeeded, address retrieval complete
2. Return to the application and go to the authentication screen
3. Press the signature button, but the metamask does not transition and not even a signature appears.

**Comment by quetool** [comment]
Hello, @iseruuuuu
Did you call `_w3mService.launchConnectedWallet();` right before your `walletConnect.web3App!.request()` call? Did you try some other Wallet?

On a side note, this 👇 is wrong:
```
includedWalletIds: {metamask},
featuredWalletIds: {metamask},
excludedWalletIds: {metamask},
```
What's your goal here? If you want to show only Metamask (which I don't recommend) you would just use `includedWalletIds: {metamask}`, that's enough.

**Comment by iseruuuuu** [comment]
@quetool 
Thanks for replay🙇

> On a side note, this 👇 is wrong:
> includedWalletIds: {metamask},
> featuredWalletIds: {metamask},
> excludedWalletIds: {metamask},
>What's your goal here? If you want to show only Metamask (which I don't recommend) you would just use includedWalletIds: {metamask}, that's enough.

- I try to fix it.


> Did you try some other Wallet?

- For other wallets, we are assuming only Metamask signatures, so we do not plan to try others

> Did you call _w3mService.launchConnectedWallet(); right before your walletConnect.web3App!.request() call? 
- Is the following assumption correct for implementation? I was able to open the meta mask, but no signature appeared.
```dart
await walletConnect.launchConnectedWallet();
final signedMessage = await walletConnect.web3App!.request(
    chainId: 'eip155:1',
    topic: walletConnect.session?.topic ?? '',
    request: SessionRequestParams(
    method: 'personal_sign',
    params: ['0x$encoded', address],
   ),
 );
```

**Comment by quetool** [comment]
> Is the following assumption correct for implementation?

Nope, it's totally fair if you want to use only Metamask, for that it's enough to just use `includedWalletIds: {metamask},`

I asked to try some other wallets just to check if could be an issue with Metamask alone or a broader issue.

**Comment by iseruuuuu** [comment]
@quetool 
Thank you.
As an additional matter to share, I did the above implementation on iOS and was able to confirm that the transition to the meta mask was correct and the signature process was issued. Therefore, I felt that there might be a problem with Android.

Also, I have tried to describe the AndroidManifest and other descriptions with reference to the SAMPLES, but it does not work.

As for the specific Android status,
- Metamask is opened.
- The application crashes without processing the signature.

**Comment by quetool** [comment]
Do you mind sharing a complete reproducible code? I'd like to see at the crash.

**Comment by crcdng** [comment]
Might have ran into the same problem. 

I was following the video in the official tutorial https://docs.walletconnect.com/web3modal/flutter/installation#tutorial

Remark: In the video at https://youtu.be/v_M2buHCpc4?t=1149, also in the [gist](https://gist.github.com/boidushya/e4063a409268c1b7bbc633d95663a918) the signMessage method is:

```dart
void signMessage() async {
    _w3mService.launchConnectedWallet();
    await _w3mService.request(
      topic: _w3mService.session?.topic ?? '',
      chainId: 'eip155:$chainId', // Connected chain id
      request: SessionRequestParams(
        method: 'personal_sign',
        params: ['Sign this', _w3mService.address],
      ),
    );
  }
```

However the params list entry `_w3mService` of type `W3MService` does not have a property `address`, see here: https://pub.dev/documentation/web3modal_flutter/latest/services_w3m_service_w3m_service/W3MService-class.html. It seems the property has been removed. Because I did not find any information on this, I guessed `_w3mService.session!.address` instead. `_w3mService.session!.address` does indeed return a String with the account address of the connected (Metamask) wallet. 

I previously had connected the app to the wallet with the `W3MConnectWalletButton` and the button still showed 'connected'. When calling the `signMessage` method, the wallet popped up and returned to the app which crashed (w3m_service.dart, line 959) with

```_$JsonRpcErrorImpl (JsonRpcError(code: 5000, message: {"code":-32602,"message":"Invalid parameters: must provide an Ethereum address."}))
```

I tried disconnecting and reconnecting the wallet and now it works. So the cause was possibly an expired or disconnected session while the `W3MConnectWalletButton` still displayed `connected` while the error message and the crash site were not helpful. 

Hope that information helps others who run into the problem. It would be cool to have a code snippet showing how to reset the `W3MConnectWalletButton` when a disconnect / expiry event happens.

**Comment by quetool** [comment]
Hello @crcdng !
Indeed the proper address is in the session as you mention `_w3mService.session!.address!`. I will go over Boidu's video and check for inconsistencies and fix them, thanks for pointing it out.

Regarding the `W3MConnectWalletButton` state I'll check what could be happening, however I have never faced such scenario if I use `onModalConnect` and `onModalDisconnect` events to setState() accordingly.

It is true however that the button should have n internal state mechanism working. I'll check and get back to you. Thanks!

**Comment by iseruuuuu** [comment]
I am sorry to reply.
I checked AndroidManifest and try change　scheme, host path and success to sign with metamask🙌

**Comment by quetool** [comment]
Wonderful @iseruuuuu! By the way, just a note, you shouldn't await `launchConnectedWallet();`. I believe since latest version that is not an async method anymore but in any case that could be an issue as well, so please remove the await from `await walletConnect.launchConnectedWallet();`
