### ISSUE TITLE
I get an infinite loading screen after connecting the wallet 

### ISSUE THREAD

**Issue by AndriiVivcharenko** [WalletConnect/Web3ModalFlutter#127]
**Describe the bug**
I get infinite loading in the modal after connecting the wallet when using version 3.2.0. I don't get any exceptions or error log output.

This issue doesn't occur with version 3.0.21
I can't test it with versions 3.1.0-3.1.3 due to this issue - https://github.com/WalletConnect/Web3ModalFlutter/issues/123. 

Tried the following wallets:
- 1inch wallet
- Metamask
- Trust Wallet
- Blockchain.com
- SafePal
- Coinbase Wallet

The same thing happens with each of them.

**To Reproduce**
1. Create new Web3App instance
```dart
  Web3App wcClient = await Web3App.createInstance(
    projectId: dotenv.env['WC_PROJECT_ID']!,
    metadata: const PairingMetadata(
      name: 'Name',
      description: 'Description',
      url: 'Url',
      icons: ['Icon'],
      redirect: Redirect(
        native: 'app://',
        universal: 'Url',
      ),
    ),
  );
```

2. Create new W3MService

```dart
final W3MService w3mService = W3MService(web3App: wcClient);
await w3mService.init();
```

3. Open the modal somewhere in the app

```dart
await w3mService!.disconnect();
await w3mService.openModal(navigatorKey.currentContext!);
```

**Expected behavior**
the wallet should be connected after the redirection from the wallet.

**Screenshots**
![IMG_0216](https://github.com/WalletConnect/Web3ModalFlutter/assets/91941098/5e26eb71-a7d8-48f9-ac63-fe8d53dc090a)

**Smartphones:**
 - iPhone 8 Plus - iOS 16.7.7
 - iPhone x - iOS 16.7.7
 - Xiaomi Mi9T Pro - Android 11

**Comment by quetool** [comment]
Hello @AndriiVivcharenko! At first glance, why are you disconnecting before opening?

> Open the modal somewhere in the app
> await w3mService!.disconnect();
> await w3mService.openModal(navigatorKey.currentContext!);

Also, you can test versions 3.1.0-3.1.3, just use the regular initialization, the one [described in the docs](https://docs.walletconnect.com/web3modal/flutter/options#w3mservice-initialization). There's no need to create a Web3App instance first, W3MService will create it for you.

**Comment by quetool** [comment]
Any console log that you? Or snippet code to reproduce? Do you mind sharing your projectId? Is perfectly safe to share it

**Comment by AndriiVivcharenko** [comment]
Just tried it in an empty project and with my project ID it works fine. I'll need some time to figure out the exact steps to reproduce in an empty project

**Comment by quetool** [comment]
> Just tried it in an empty project and with my project ID it works fine. I'll need some time to figure out the exact steps to reproduce in an empty project

What do you mean exactly?

**Comment by 5eeman** [comment]
I'm facing pretty much the same problem with 3.1.2.
It feels like some callback is not being invoked on return from wallet app.

**Comment by quetool** [comment]
Guys, I will need a minimum piece of code, otherwise it's quite difficult to help.

**Comment by 5eeman** [comment]
Ok, so I'm trying plain example from master branch.
I've added my project id and trying to connect to Metamask.
No connect dialog is being shown inside.
That doesn't feel right to me.

**Comment by 5eeman** [comment]
Ok, I've tested also Trust and it works as a charm...
But I need MM to test amoy 🤦🏻

**Comment by AndriiVivcharenko** [comment]
I managed to fix it. I have some logic for the `onSessionConnect` event that opens a dialog box in the same context. 
```dart
  await w3mService.init();
  wcClient.onSessionConnect.subscribe(wrapOnSessionConnect(ref, context));
  
  ///////////
  
  void Function(SessionConnect?) wrapOnSessionConnect(
    WidgetRef ref, BuildContext context) {
  return (SessionConnect? args) {

    // some code here
    showDialog(context: context, builder: (context) => AuthPopup());
  };
}
  
```
This event gets triggered when the modal window is still open. I just moved my `showDialog` after

```dart
await w3mService.openModal(navigatorKey.currentContext!);
// showDialog
```

and now it works fine.

**Comment by quetool** [comment]
> Ok, I've tested also Trust and it works as a charm... But I need MM to test amoy 🤦🏻

@5eeman I have faced issues myself with Amoy on Metamask although every other chain seems to be working fine, even Sepolia. Try by adding Amoy manually on Metamask then connecting again with Web3Modal

@AndriiVivcharenko this is something I still don't understand what you mean 👇 

> Just tried it in an empty project and with my project ID it works fine. I'll need some time to figure out the exact steps to reproduce in an empty project

However, about this 👇

> This event gets triggered when the modal window is still open. I just moved my showDialog after

Events are independent from the modal itself, events are essentially messages thrown by the relay in regards of different actions so yeah, it could happen that `onSessionConnect` triggers a few milliseconds before the modal closes but that shouldn't be an issue UX wise. If you are on the latest version of the SDK try using `w3mService.onModalConnect.subscribe()` instead. https://docs.walletconnect.com/web3modal/flutter/events

**Comment by quetool** [comment]
Also @AndriiVivcharenko better to subscribe to events before init(), check the example https://github.com/WalletConnect/Web3ModalFlutter/blob/master/example/lib/home_page.dart#L110

**Comment by AndriiVivcharenko** [comment]
> @AndriiVivcharenko this is something I still don't understand what you mean 👇
> 
> > Just tried it in an empty project and with my project ID it works fine. I'll need some time to figure out the exact steps to reproduce in an empty project

I created an empty flutter project and started dragging pieces of code from the main project until I figured out what the root cause was. That's what I meant.

> Events are independent from the modal itself, events are essentially messages thrown by the relay in regards of different actions so yeah, it could happen that `onSessionConnect` triggers a few milliseconds before the modal closes but that shouldn't be an issue UX wise. If you are on the latest version of the SDK try using `w3mService.onModalConnect.subscribe()` instead. https://docs.walletconnect.com/web3modal/flutter/events

> Also @AndriiVivcharenko better to subscribe to events before init(), check the example https://github.com/WalletConnect/Web3ModalFlutter/blob/master/example/lib/home_page.dart#L110

I just made these changes and it seems to be working fine and stable now. Thank you
