### ISSUE TITLE
Wallet authorization doesn't work for me

### ISSUE THREAD

**Issue by AlexSeednov** [WalletConnect/Web3ModalFlutter#132]
**Describe the bug**

I need to integrate in mobile app authorization by Metamask and Trust wallet via Wallet Connect. I tried several ways by different documentations and examples (all details below) but didn't find fully workable variant.

---

**Tested on smartphones:**
iOS:
 - Device: iPhone 12 Pro
 - OS: iOS 17.4.1
 - Browser: Safari
 - Version: actual

Android:
 - Device: Pixel 8 Emulator
 - OS: Android 14.0
 - Browser: Chrome
 - Version: actual

Also partially was tested on several other iOS and Android devices with the same results.

**Environment:**
Now I'm working on Flutter 3.22.0 (Dart 3.4.0) with package web3modal_flutter: 3.2.0
Yesterday it was Flutter 3.16.4 (Dart 3.2.3) with package web3modal_flutter: 3.1.2
The same results.

---

**Details**
Earlier I used web3modal_flutter package for wallet connection via pre-created bottom modal (W3MService -> openModal function) and it works perfect, but I can not find the same way for authorization. 

So my **first question** - can I somehow realize authorization similar to connecting wallet flow? Ideally just called the same bottom modal, where user will select wallet, this wallet will be opened to authorization request and return all necessary data back to the app.

To achieve this I firstly tried to use [WalletConnect Auth API](https://docs.walletconnect.com/api/auth/overview) - this work fine, but only on android and only for Trust wallet:
- Trust on Android: Working fine, but without returning to the app from wallet
- Trust on iOS: got error `JsonRpcError: Method Unsupported (code: 10001)`
- Metamask on Android: Endless "Connecting to MetaMask" after opening Metamask
- Metamask on iOS: Endless "Connecting to MetaMask" after opening Metamask

Secondly I tried to smth like [this](https://gist.github.com/quetool/f934b449ed0027f8b435622a2719328a) - use Web3App and authenticate in two steps: connect to wallet (Web3App -> connect function) then auth by wallet (Web3App -> requestAuth). Results was similar:
- Trust on Android: Working fine, but without returning to the app from wallet on the second step (after authorization confirmed in wallet)
- Trust on iOS: got error `JsonRpcError: Method Unsupported (code: 10001)`
- Metamask on Android: Success connection, but without auth functionality in wallet after reopening with requestAuth
- Metamask on iOS: Success connection, but without auth functionality in wallet after reopening with requestAuth

Then I tried combine way: firstly set a connection by opening bottom modal (W3MService -> openModal function) with created Web3App and after this make an authorization request (Web3App -> requestAuth). And got the same results:
- Trust on Android: Working fine, but without returning to the app from wallet on the second step (after authorization confirmed in wallet)
- Trust on iOS: got error `JsonRpcError: Method Unsupported (code: 10001)`
- Metamask on Android: Success connection, but endless "Connecting to MetaMask" after reopening with requestAuth
- Metamask on iOS: Success connection, but without auth functionality after reopening with requestAuth

After third failure I decided to write all of this as issue.. For this I also prepared separated project with all three implemented ways - https://github.com/AlexSeednov/test

I thought it may be because of possible collisions in current big project but no, empty project has the same results..

Sources of the three ways:
- Via WalletConnect Auth API - https://github.com/AlexSeednov/test/blob/main/lib/auth_directly.dart
- Web3App + requestAuth - https://github.com/AlexSeednov/test/blob/main/lib/auth_web3app.dart
- Web3App + openModal + requestAuth  - https://github.com/AlexSeednov/test/blob/main/lib/auth_modal.dart

The **second question** - what am I doing wrong? Please help me, my head is near to end

After getting data from wallet connect we decided to use this data for verifying a wallet:
- address
- iat
- signature
```
      final String walletAddress = AddressUtils.getDidAddress(authResponse.result!.p.iss);
      final String iat = authResponse.result!.p.iat;
      final String signature = authResponse.result!.s.s;
```
Please confirm - is it enough to securely user validation or not? This is my **third, the last question**.

Thank you for your time! If you need some more additional information - please let me know, will send all necessary.

**Comment by quetool** [comment]
Hello @AlexSeednov ! Thank for your detailed report!
I would start by saying that if your implementation works on Trust Wallet on Android I would say there's nothing wrong with your implementation nor with ours. (The fact that Trust does not redirect back to the Dapp is a separate issue on **their** side. They should call back your redirect object from your metadata)

That being said, I believe most wallets does not support `wc_authRequest` method (which is the RPC method being called on `web3app.requestAuth()`) and that is why you are seeing `JsonRpcError: Method Unsupported (code: 10001)` error on Trust iOS and possible other issues with other wallets.
If you really want to be sure your implementation is fine you can test it out with our React sample wallet here https://react-wallet.walletconnect.com which supports such method.

That being said, I have good news for you: There's a new feature that we are implementing and that Wallets are adopting quickly and it's called 1-Click Auth. You can read more here https://docs.walletconnect.com/web3wallet/authenticatedSessions but under the hood it's about a new RPC method `wc_sessionAuthenticate` where you get to **authenticate** (leveraging CAIP-222 https://chainagnostic.org/CAIPs/caip-222) and **connect** with the wallet in just 1 step.

We are implementing it in Flutter currently and it might take a couple of weeks but in the meantime you can test it out here https://lab.web3modal.com/library/wagmi-siwe/ by selecting Trust or Binance wallets.

Once I finish the implementation on Flutter I would be happy if you test it out so I'll reach out to you!

Demo 1-Click Auth

https://github.com/WalletConnect/Web3ModalFlutter/assets/14978705/91dd7718-8742-4a78-8ade-a6a41fba5298
