### ISSUE TITLE
Infinite loading email connect field

### ISSUE THREAD

**Issue by AlexScotte** [WalletConnect/Web3ModalFlutter#137]
**Describe the bug**
Cannot acces to email field, there is an infinite activity indicator that is loading (v3.2.1)
https://github.com/WalletConnect/Web3ModalFlutter/assets/53000621/640cc132-b5cc-4477-a007-41bd57a2efa6

**To Reproduce**
Enable the email connection in W3MService
```dart
_w3mService = W3MService(
      projectId: '0c4489e57498a892c4fca2fb33e93f36',
      metadata: const PairingMetadata(
        name: 'Web3Modal Flutter Example',
        description: 'Web3Modal Flutter Example',
        url: 'https://www.walletconnect.com/',
        icons: ['https://walletconnect.com/walletconnect-logo.png'],
        redirect: Redirect(
          native: 'w3m://',
          universal: 'https://www.walletconnect.com',
        ),
      ),
      enableEmail: true,
    );
```
Add a W3MConnectWalletButton
Click on it
Cannot click on the email field and there is an infinite activity indicator

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
Android samsung S6 and android one+

**Additional context**
full code 

```dart
import 'package:flutter/material.dart';
import 'package:web3modal_flutter/web3modal_flutter.dart';

class SignInPage extends StatefulWidget {
  const SignInPage({super.key});

  @override
  State<SignInPage> createState() => _SignInPageState();
}

class _SignInPageState extends State<SignInPage> {
  late W3MService _w3mService;

  @override
  void initState() {
    super.initState();
    initializeState();
  }

  void initializeState() async {
    W3MChainPresets.chains.putIfAbsent(_chainId, () => _sepoliaChain);

    _w3mService = W3MService(
      projectId: '0c4489e57498a892c4fca2fb33e93f36',
      metadata: const PairingMetadata(
        name: 'Web3Modal Flutter Example',
        description: 'Web3Modal Flutter Example',
        url: 'https://www.walletconnect.com/',
        icons: ['https://walletconnect.com/walletconnect-logo.png'],
        redirect: Redirect(
          native: 'w3m://',
          universal: 'https://www.walletconnect.com',
        ),
      ),
      enableEmail: true,
    );

    // _w3mService.onModalConnect.subscribe((ModalConnect? event) {});

    await _w3mService.init();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        W3MConnectWalletButton(service: _w3mService),
        W3MNetworkSelectButton(service: _w3mService),
        W3MAccountButton(service: _w3mService),
      ],
    );
  }
}

const _chainId = "11155111";

final _sepoliaChain = W3MChainInfo(
  chainName: 'Sepolia',
  namespace: 'eip155:$_chainId',
  chainId: _chainId,
  tokenName: 'ETH',
  rpcUrl: 'https://rpc.sepolia.org/',
  blockExplorer: W3MBlockExplorer(
    name: 'Sepolia Explorer',
    url: 'https://sepolia.etherscan.io/',
  ),
);
```

**Comment by quetool** [comment]
Thank you very much @AlexScotte for the report! Allow me some time to investigate and I'll be back to you

**Comment by quetool** [comment]
Hello @AlexScotte Could you add `logLevel: LogLevel.error,` in your W3MService instance  and also add a listener to `_w3mService.onModalError` just to check if you see something valuable in the console?

So basically your code will be this:

```dart
import 'package:flutter/material.dart';
import 'package:web3modal_flutter/web3modal_flutter.dart';

class SignInPage extends StatefulWidget {
  const SignInPage({super.key});

  @override
  State<SignInPage> createState() => _SignInPageState();
}

class _SignInPageState extends State<SignInPage> {
  late W3MService _w3mService;

  @override
  void initState() {
    super.initState();
    initializeState();
  }

  void initializeState() async {
    W3MChainPresets.chains.putIfAbsent(_chainId, () => _sepoliaChain);

    _w3mService = W3MService(
      projectId: '0c4489e57498a892c4fca2fb33e93f36',
      logLevel: LogLevel.error,
      metadata: const PairingMetadata(
        name: 'Web3Modal Flutter Example',
        description: 'Web3Modal Flutter Example',
        url: 'https://www.walletconnect.com/',
        icons: ['https://walletconnect.com/walletconnect-logo.png'],
        redirect: Redirect(
          native: 'w3m://',
          universal: 'https://www.walletconnect.com',
        ),
      ),
      enableEmail: true,
    );

    // _w3mService.onModalConnect.subscribe((ModalConnect? event) {});
    _w3mService.onModalError.subscribe(_onModalError);

    await _w3mService.init();
  }

  void _onModalError(ModalError? args) {
    debugPrint('modal eror ${args?.toString()}');
  }
  
  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        W3MConnectWalletButton(service: _w3mService),
        W3MNetworkSelectButton(service: _w3mService),
        W3MAccountButton(service: _w3mService),
      ],
    );
  }
}

const _chainId = "11155111";

final _sepoliaChain = W3MChainInfo(
  chainName: 'Sepolia',
  namespace: 'eip155:$_chainId',
  chainId: _chainId,
  tokenName: 'ETH',
  rpcUrl: 'https://rpc.sepolia.org/',
  blockExplorer: W3MBlockExplorer(
    name: 'Sepolia Explorer',
    url: 'https://sepolia.etherscan.io/',
  ),
);
```

**Comment by AlexScotte** [comment]
Hello @quetool,
Thanks for your answer
Not sure it comes from the modal error event because i do not hit the break point that i put inside but now i have this in the console 
![image](https://github.com/WalletConnect/Web3ModalFlutter/assets/53000621/cf6abe8f-b623-4613-8f63-f615485f5728)


other message in the console that can help you too
![image](https://github.com/WalletConnect/Web3ModalFlutter/assets/53000621/2311c7a0-1eba-4920-a25b-2e90cb3831de)

**Comment by quetool** [comment]
Thanks @AlexScotte, could you confirm your device is connected to internet? Asking just to discard that possible error, most of the times "Failed host lookup" happens when device is not connected to internet.

**Comment by AlexScotte** [comment]
I tested again on my mobile to be sure that it's not a wifi issue, I do not have the same error in the debug console, so maybe i had an issue on my tablet but still the same behavior 

https://github.com/WalletConnect/Web3ModalFlutter/assets/53000621/2efb15bf-bc9c-4e5b-b729-7fddf37bf3bc

The full debug console, i hope it will help 
<img width="1657" alt="image" src="https://github.com/WalletConnect/Web3ModalFlutter/assets/53000621/89344649-e8c9-4565-9534-e12d23645ed6">
<img width="1649" alt="image" src="https://github.com/WalletConnect/Web3ModalFlutter/assets/53000621/681ba362-bb12-483b-b683-53e7453f220e">

**Comment by quetool** [comment]
Could you add your bundleId and packageName inside cloud configuration? 

1. LogIn into https://cloud.walletconnect.com/
2. Open Dashboard and scroll down to Mobile Application IDs menu
3. Add your iOS Bundle ID and your Android Package Name

Your Android Package Name it seems to be `com.example.boilerplate wallet_web3` so should look like this

![Screenshot 2024-06-05 at 19 38 21](https://github.com/WalletConnect/Web3ModalFlutter/assets/14978705/db26987d-2d5f-4b5b-8c3d-3441231e6b87)

After this, please wait around 20 minutes and try again.

**Comment by quetool** [comment]
Hello @AlexScotte ! I identified the issue.
From one side, you do have to whitelist your bundleId and packageName as I mentioned in my previous comment (I'll add this into the docs)
On another side, there's an initialization bug that is affecting only Android. If you have an iOS device or simulator you can keep your development there and I'll push a fix for Android tomorrow. 

Thank you very much for this report!

**Comment by AlexScotte** [comment]
I added the package name in cloud wallet connect, I will test again after the fix
Thank you

**Comment by quetool** [comment]
GM @AlexScotte ! Do you mind trying now if it's working? 🙏

**Comment by AlexScotte** [comment]
GM @quetool all is working great now ! Thank you for the quick fix

https://github.com/WalletConnect/Web3ModalFlutter/assets/53000621/a9ea3142-3f4f-49f6-a2ef-481009be62d5

**Comment by quetool** [comment]
Wonderful! Depending on your internet quality the loading behavior could take more or less! 💪

**Comment by AlexScotte** [comment]
Sorry @quetool does the email connection available for windows app ? I have an issue on the initialization of W3MService but i wanted to be sure before creating a new ticket
The error appears only if I activate the enbleEmail: true

**Comment by AlexScotte** [comment]
Thanks for the informations !
