### ISSUE TITLE
Coinbase Integration

### ISSUE THREAD

**Issue by samuel2629** [WalletConnect/Web3ModalFlutter#144]
Hi,

This is what i tried to integrate Coinbase as a working wallet but it still fails (but works properly with Meta, rainbow, trust...).

1. I used Web3ModalFlutter 3.2.2 and as stated in the doc i override dependency for coinbase_wallet_sdk. But doing so i have several errors in coinbase_service saying that BigInt? can't be assigned to BigInt and same thing with String.

2. I used Web3ModalFlutter preRelease version 3.3.0-beta04 since i saw that the issue with coinbase was merged (it seems like so to me at least) so here when i click connect and choose coinbase it opens coinbase and asks me to connect but back on the app, i have an error opening wallet.

Do you have any news on that please? Or do you need more info if so please let me know which ones?

Thank you

**Comment by quetool** [comment]
Hello @samuel2629! This is very strange, do you mind share a reproducible code? Maybe a little project with your implementation where I can reproduce the issue? Also a video might help!

**Comment by samuel2629** [comment]
Hi, here the video and the implementation

`w3mService.value = W3MService(
      context: context,
      projectId: projectID,
      logLevel: LogLevel.error,
      metadata: PairingMetadata(
        name: name,
        description: desc,
        url: url,
        icons: icons,
        redirect: Redirect(
          native: nativeUrl,
          universal: universalUrl,
        ),
      ),
    );`

For the opening the modal since i'm using a custom widget when onTap i call the function w3mService.openModal(context)

In the manifest i added org.toshi

and here is the video 

https://github.com/WalletConnect/Web3ModalFlutter/assets/21241669/d6cf0b6e-cf82-4ed0-9900-29c872d79610

I just added package name in wallet connect page settings don't know if it's supposed to change anything.
Also i only have mobile, should i configure "Verify Domain" and "Origin Allowlist"? Does it change anything? 

Thank you

**Comment by quetool** [comment]
Hello @samuel2629 ! I may have found the issue! I'll try to push a fix today!

**Comment by samuel2629** [comment]
Great thank you ! 
Could you please let me know? 

Thank you

**Comment by samuel2629** [comment]
Just another thing not related at all but don't know where to say that.
I tried SIWE integration in pre release, i think there is something strange, in the createMessage function, there is this return : return _w3mService.formatMessage(args);

Issue is that the _siweConfig is passed as a parameter of _w3mService, so this is an impossible loop.

Maybe i didn't get it right, just wanted to let you know

**Comment by quetool** [comment]
> Great thank you ! Could you please let me know?

Sure!

> Issue is that the _siweConfig is passed as a parameter of _w3mService, so this is an impossible loop.

I get the point, it's a good observation, however, `createMessage:` function callback from _siweConfig is getting called once _w3mService is already instantiated so there's no issue. If you run the sample app in the repo you can try it out.

But it's a good point tho, I'll try to move it to some Util class instead of having it in the main one.

**Comment by samuel2629** [comment]
Great i'll try that 👍

**Comment by quetool** [comment]
Hello @samuel2629 ! Coinbase issue has been addressed and a new version has been deployed (`3.3.0-beta05`). 

That being said, even if you can now safely use our SDK the whole Coinbase fix consist in 2 parts, one in our side (addressed) and another in one in Coinbase's side, which is under review https://github.com/MobileWalletProtocol/wallet-mobile-sdk/pull/346 and could take some time to be merged and deployed.

I have also addressed your `_w3mService.formatMessage(args);` suggestion and now you would need to use `AuthSignature.formatMessage(args);` 👌

**Comment by samuel2629** [comment]
Thank you @quetool for being so effective 🥇

**Comment by samuel2629** [comment]
Just to let you know @quetool i tried with Android (not ios, but it seems that you notified them that in IOS it is working ok) and everything seems to work at least to connect and sign with Coinbase.

**Comment by quetool** [comment]
Yes, that's correct, it's only an Android issue

**Comment by samuel2629** [comment]
> Yes, that's correct, it's only an Android issue

It worked with Android tho
