### ISSUE TITLE
How to call a Smartcontract write function that requires passing Id, name and USDC Token

### ISSUE THREAD

**Issue by Mindsetter** [WalletConnect/Web3ModalFlutter#151]
I reviewed the documentation and the examples but couldn't get the right picture of implementing this. 
1. Should I add the USDC and Smart Contract abi.json files to my folder?
2. How do I pass the USDC token together with the rest of the parameters when the write function of my smart contract is called 

**Contract Address**
```
0x0056a69983F0a513C92A59A67f7c233f1c2c1A3C
```

**ABI**
```

[
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_usdcTokenAddress",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "enum Akoko.Status",
        "name": "status",
        "type": "uint8"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "recipient",
        "type": "string"
      }
    ],
    "name": "OrderPlaced",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_id",
        "type": "uint256"
      }
    ],
    "name": "payout",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "Payout",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_id",
        "type": "uint256"
      },
      {
        "internalType": "string",
        "name": "_recipient",
        "type": "string"
      },
      {
        "internalType": "uint256",
        "name": "_usdcAmount",
        "type": "uint256"
      }
    ],
    "name": "placeOrder",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "escrowBalances",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "orders",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "id",
        "type": "uint256"
      },
      {
        "internalType": "enum Akoko.Status",
        "name": "status",
        "type": "uint8"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      },
      {
        "internalType": "string",
        "name": "recipient",
        "type": "string"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "owner",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "usdcToken",
    "outputs": [
      {
        "internalType": "contract IERC20",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
]

```

Version: web3modal_flutter: ^3.2.2

Thank you

**Comment by quetool** [comment]
Hello @Mindsetter! Yes, you should add the ABI, checkout out how it's done in the example folder

Here: https://github.com/WalletConnect/Web3ModalFlutter/blob/master/example/lib/utils/crypto/eip155_service.dart#L245
And here: https://github.com/WalletConnect/Web3ModalFlutter/blob/master/example/lib/utils/crypto/test_data/test_contract.dart

**Comment by Mindsetter** [comment]
Hi @quetool 

Thanks for the heads-up. I have checked out the examples but I have follow-up questions.

I'm new to web3 so kindly pardon me: 

Do I need to create two(2) DeployedContract objects for the USDC Token contract and my CustomSmartContract?

**I assume that from the example, the Deployment contract was created for AAVE Token which in my case will be the USDC Token**
```
    // Create DeployedContract object using contract's ABI and address
    final deployedContract = DeployedContract(
      ContractAbi.fromJson(
        jsonEncode(AAVESepoliaContract.contractABI),
        'AAVE Token (Sepolia)',
      ),
      EthereumAddress.fromHex(AAVESepoliaContract.contractAddress),
    );
    
    ```
    After calling the transfer function from the USDC Token contract, kindly help me with the steps to pass the USDC Token Value to my CustomSmartContract as it requires the USDC Amount.
     
     Lastly is there a way to show the USDC Token a user holds on the Mobile App after the wallet is connected? Currently, only the native coin of the chain shows.
     
     Thank you in advance

**Comment by quetool** [comment]
> Do I need to create two(2) DeployedContract objects for the USDC Token contract and my CustomSmartContract?

I'm not expert on Smart Contracts but I don't think so. You should interact with one contract at a time, and I assume it should be the contract you shared with me before, your custom contract, otherwise what would be the point of that contract? What does it do?
If you want to just interact with USDC, AAVE, USDT or any other other you don't need a custom contract, you can interact directly with them and there's an useful example in the example app of the repo https://github.com/WalletConnect/Web3ModalFlutter/blob/630950f5f465d3e13143911b1a4e8ee076a389b3/example/lib/utils/crypto/eip155_service.dart#L326

> Lastly is there a way to show the USDC Token a user holds on the Mobile App after the wallet is connected? Currently, only the native coin of the chain shows.

You could use the /balance endpoint of our blockchain API, this will give the balance of all the tokens for the account. (We are planning to add this feature in this very SDK in the near future) https://specs.walletconnect.com/2.0/specs/servers/blockchain/blockchain-api#balance

**Comment by quetool** [comment]
> After calling the transfer function from the USDC Token contract, kindly help me with the steps to pass the USDC Token Value to my CustomSmartContract as it requires the USDC Amount.

The contract ABI you share has 6 functions: payout, placeOrder, escrowBalances, orders, owner, usdcToken... There's no transfer function so not sure what you want to do.

**Comment by Mindsetter** [comment]
Hi @quetool 

Thanks for the explanation and support.

I tried calling a payable function with parameters and was redirected to my connected Metamask but it failed to show the requested prompt. Initially, I tried with the AAVE Token contact from the example folder without having any issues. 

This time I'm transferring a token with parameters.

```dart
  Future<dynamic> callAkokoContract({
    required W3MService w3mService,
    required String uuid,
    required int id,
    required String recipient,
  }) async {
    final deployedContract = DeployedContract(
      ContractAbi.fromJson(
        jsonEncode(AkokoContract.contractABI),
        'Akoko',
      ),
      EthereumAddress.fromHex(AkokoContract.contractAddress),
    );

    w3mService.launchConnectedWallet();
    final res = w3mService.requestWriteContract(
        topic: w3mService.session!.topic ?? '',
        chainId: 'eip155:11155111',
        deployedContract: deployedContract,
        functionName: 'placeOrder',
        transaction: Transaction(
          from: EthereumAddress.fromHex('${w3mService.session!.address}'),
          to: EthereumAddress.fromHex(
              '0xA02136cccBD67BC00E9e9344d4B6044a2723Ef0f'),
          value: EtherAmount.fromInt(EtherUnit.finney, 1), // == 0.010
        ),
        parameters: [
          uuid,
          id,
          recipient,
        ]);

    debugPrint('Test2: $res');
  }
  
  ```
  
  New ABI Code used
  
  https://gist.github.com/Mindsetter/c69ad850293b0093703868f85b384c22
