### ISSUE TITLE
Binance sign request

### ISSUE THREAD

**Issue by samuel2629** [WalletConnect/Web3ModalFlutter#154]
I'm trying to implement the connect and sign with Binance, connection is ok but when trying to sign, it asks to go to pro version and when going to pro version it's saying that this link doesn't work and to check if the app is up to date (of course i already check) the logic of the code is very basic and works with a lot of wallets like meta, trust, coinbase, rainbow...

Any idea ? Thank you

![WhatsApp Image 2024-07-18 at 15 13 48](https://github.com/user-attachments/assets/762225b8-ecfe-48bf-87ec-ac72f66ab0d4)
![WhatsApp Image 2024-07-18 at 15 13 49](https://github.com/user-attachments/assets/29357c91-43c5-464d-877b-c6201f5637c3)

**Comment by quetool** [comment]
Can you share steps to reproduce and code?

**Comment by samuel2629** [comment]
First : 

```
w3mService.value = W3MService(
      context: context,
      projectId: projectID,
      logLevel: LogLevel.error,
      metadata: PairingMetadata(
        name: name,
        description: desc,
        url: url,
        icons: icons,
        redirect: Redirect(
          native: nativeUrl,
          universal: universalUrl,
        ),
      ),
    );
```
    
 Then to connect : 

`w3mService.openModalView()`

And to sign : 

```
w3mService.value!.launchConnectedWallet();
final session = widget.w3mService.session!;
EIP155.callMethod(
          w3mService: w3mService,
          topic: session.topic ?? "",
          method: method,
          chainId: chainMetadata.w3mChainInfo.namespace,
          address: address.toLowerCase(),
        );
```

It is very basic and works with a lot of wallets but not binance

**Comment by quetool** [comment]
Hello @samuel2629, sorry for the late response. Anyway this is not useful to me, I would need the actual implementation of `EIP155.callMethod()`, basically I would need to see how you call `w3mService.request()` method.

**Comment by quetool** [comment]
Hello @samuel2629! I'll close this for now, feel free to re-open if issue still exists.
