### ISSUE TITLE
W3MConnectWalletButton connect

### ISSUE THREAD

**Issue by 15112415279** [WalletConnect/Web3ModalFlutter#158]
When clicking MetaMask or OKX Wallet, after the redirection, it remains stuck on "connecting".

**Comment by quetool** [comment]
Hello! Could you share steps to reproduce? implementation code or anything that would help me reproduce the issue?

**Comment by 15112415279** [comment]
Of cause.  After the `init` method, I use `openModal` to bring up the bottom WalletConnect modal. After clicking to jump to the corresponding wallet, those wallets remain in the connecting state. The detailed connection parameters are wc:81afecef5e77ddd0966c87a5a7373f9d7131ce7ad2e6b2aa8cd01b2252fd23d2@2?relay-protocol=irn&symKey=f4a86ac46a61b62017f5b329991dfa230b9a187fd4e6295140b238f38121fe3d&methods=[wc_sessionPropose,wc_sessionRequest],[wc_authRequest]. I believe the method parameter should only be `methods=wc_sessionAuthenticate`, but passing it as `methods=[[wc_sessionAuthenticate]]` still doesn't work.

**Comment by 15112415279** [comment]
Of cause.  After the init method, I use openModal to bring up the bottom WalletConnect modal. After clicking to jump to the corresponding wallet, those wallets remain in the connecting state. The detailed connection parameters are wc:***@2?relay-protocol=irn&symKey=***&methods=[wc_sessionPropose,wc_sessionRequest],[wc_authRequest]. I believe the method parameter should only be methods=wc_sessionAuthenticate, but passing it as methods=[[wc_sessionAuthenticate]] still doesn't work.

**Comment by 15112415279** [comment]
w3mService.web3App?.onSessionConnect.subscribe((args) {
      connectAddress();
    });
    w3mService.init();
w3mService.openModal(context);

**Comment by quetool** [comment]
Hello @15112415279! Sorry for the late response, Is this still an issue?

**Comment by 15112415279** [comment]
No .Thanks Bro
