### ISSUE TITLE
No redirecting on IOS

### ISSUE THREAD

**Issue by Airking26** [WalletConnect/Web3ModalFlutter#159]
On IOS only when trying to connect with some wallets like Metamask or Rainbow either i'm trying to connect or sign a message after that the wallet displays the popup to execute the action (connecting, signing...) the wallet doesn't go back to the app but rather displays a message saying to go back manually.

![image0](https://github.com/user-attachments/assets/6bb51a89-651c-47b1-9588-b4cf84c2aa1c)
![image1](https://github.com/user-attachments/assets/56d19b24-e0ef-499c-ae7b-2c3deff50d8a)

I followed the official doc, this is my info.plist : 

```
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLName</key>
			<string>io.airking.sirkl</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>sirkl</string>
			</array>
		</dict>
	</array>
```

and in W3MService i configured Redirect > native to : sirkl://

**Comment by quetool** [comment]
Hello @Airking26, thanks for raising. This is not an issue in our SDK rather an issue in the wallet itself. Wallet have been warned about this and they will need to fix it if they want to be [WalletConnect Certified](https://walletconnect.com/blog/walletguide-walletconnect-certified)

**Comment by quetool** [comment]
You implementation looks good to me if you are also passing `sirkl` in your connection metadata.

**Comment by Airking26** [comment]
I do, like so : W3MService(..., metadata: PairingMetadata(..., redirect : Redirect(native: "sirkl://")))

Is Metamask not WalletConnect Certified ? Because it also has this issue.

**Comment by quetool** [comment]
Your implementation is ok. The redirection back to dapp has to be done by the wallet. Zerion Wallet does it properly, you can try that one to check your implementation. Also you can try our Web Wallet in your mobile browser https://react-wallet.walletconnect.com

**Comment by quetool** [comment]
> Is Metamask not WalletConnect Certified ? Because it also has this issue.

None is yet, they are working towards it.

**Comment by Airking26** [comment]
Ok, thank you for the answers.
