### ISSUE TITLE
open connected wallet when transaction request or write contract request

### ISSUE THREAD

**Issue by nimashahahmadian** [WalletConnect/Web3ModalFlutter#170]
I am using W3MService.requestWriteContract to do a token transaction. Is it possible to open the wallet which I have connected previously using web3modal.

what happens now is a request is sent through w3Service but user should open the wallet and accept the incoming transaction request when accepted or rejected wallet would pop.

I'm simply asking if it is possible to open the same wallet as before when using the connect option and afterwards redirect to the given app as I did in connection phase.

thanks a bunch.

**Comment by quetool** [comment]
Hey @nimashahahmadian, here's the docs 

https://docs.walletconnect.com/appkit/flutter/core/actions#launch-the-current-wallet

**Comment by nimashahahmadian** [comment]
Hey @quetool appreciate it, Thanks.
