### ISSUE TITLE
Issue on flutter version 3.22.3 and Dart SDK 3.4.4

### ISSUE THREAD

**Issue by agisrh** [WalletConnect/Web3ModalFlutter#171]
**Bug**
Cannot add package on pubspec.yaml

```And because web3dart >=2.7.2 <2.7.3 depends on wallet ^0.0.12+1 and web3modal_flutter >=3.3.1 depends on walletconnect_flutter_v2 ^2.3.1, web3modal_flutter >=3.1.0-beta03 requires walletconnect_flutter_v2 ^2.2.2-beta01 or wallet ^0.0.12+1 or web3dart ^2.7.3.
And because walletconnect_flutter_v2 >=2.2.2-beta01 depends on web3dart ^2.7.3 which depends on wallet ^0.0.13, web3modal_flutter >=3.1.0-beta03 requires wallet ^0.0.12+1.
So, because wallet depends on web3modal_flutter ^3.1.0 and wallet is 1.0.0+1, version solving failed.```

**Comment by quetool** [comment]
What package exactly are you trying to add?

**Comment by agisrh** [comment]
I added the Web3ModalFlutter package to my pubspec, but I get an error message regarding this issue.

**Comment by quetool** [comment]
Can I see your pubspec.yaml file?

**Comment by agisrh** [comment]
`name: wallet
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  web3modal_flutter: ^3.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true`

**Comment by quetool** [comment]
Thank you! Can you change environment to 
```
environment:
  sdk: '>=3.0.1 <4.0.0'
```
And try again?

**Comment by agisrh** [comment]
still issue, this message an error:

`Because web3modal_flutter >=3.3.1 depends on walletconnect_flutter_v2 ^2.3.1 which depends on web3dart ^2.7.3, web3modal_flutter >=3.3.1 requires web3dart ^2.7.3.`

**Comment by quetool** [comment]
That is weird, I just tried it myself and I had no issues.

![Screenshot 2024-09-12 at 09 01 03](https://github.com/user-attachments/assets/2edda7b9-f4d5-46a6-a132-f9160dfe2b14)

Are you sure you are not installing anything else? Also, the message is telling me you are installing `web3modal_flutter 3.3.1`, not `3.3.3` but that shouldn't be an issue anyway.

I would try the following:
1. Delete pubspec.lock file
2. run `flutter clean`
3. run `flutter pub get`

If that doesn't work then I would try adding `web3dart: ^2.7.3` as dependency override but it shouldn't be needed honestly.

```
dependency_overrides:
  web3dart: ^2.7.3
```

**Comment by agisrh** [comment]
Thank you!
this work after added web3dart: ^2.7.3

**Comment by quetool** [comment]
Hm, that's weird anyway, it shouldn't be needed at all. Could you share your `flutter doctor -v` output? I would like to recreate your environment for debugging purposes.

**Comment by agisrh** [comment]
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.6.1 23G93 darwin-arm64, locale en-ID)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.92.2)
[✓] Connected device (1 available)
[✓] Network resources

! Doctor found issues in 2 categories.
itdev@Agiss-MacBook-Air wallet % flutter doctor -v
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.6.1 23G93 darwin-arm64, locale en-ID)
    • Flutter version 3.22.3 on channel stable at /Users/itdev/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (8 weeks ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/itdev/Library/Android/sdk
    • Platform android-35, build-tools 35.0.0
    • ANDROID_HOME = /Users/itdev/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS and macOS development.
      Download at: https://developer.apple.com/xcode/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.15.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2024.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0-17.0.11b1207.24-11852314)

[✓] VS Code (version 1.92.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.96.0

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-arm64 • macOS 14.6.1 23G93 darwin-arm64

[✓] Network resources
    • All expected network resources are available.`
