### ISSUE TITLE
[feature] Add custom headers to explorer-api request

### ISSUE THREAD

**Issue by ignaciosantise** [WalletConnect/Web3ModalFlutter#3]
### What problem does this new feature solve?

Adds `user-agent` and `referer` headers in explorer-api requests

### Describe the solution you'd like

* `user-agent` that follows the pattern `<web3modal version>/<core sdk version>/<operating system>`
* `referer` containing the `name` provided in the sdk metadata (with no spaces)

example:
```js
headers: {
 user-agent: 'w3m-flutter-1.0.0/flutter-core-1.5.7/ios-16.5',
 referer: 'ExampleAppName'
}
```

**Comment by Luzzotica** [comment]
This is done as of 1.2.0
