### ISSUE TITLE
Example for web build doesn't load wallet

### ISSUE THREAD

**Issue by dev-ro** [WalletConnect/Web3ModalFlutter#41]
**Describe the bug**
The example connects properly to my wallet when I run the android build. But when I run the web build, the connect wallet button times out and stays on a spinning icon. It doesn't load the wallets or give an option for a QR code. There is no error message, just a warning "The platformViewRegistry getter is deprecated and will be removed in a future release. Please import it from `dart:ui_web` instead."

**To Reproduce**
1. Shut down android emulator
2. Open the terminal at the example folder lib/main.dart
3. flutter run --dart-define=PROJECT_ID=...
4. Select Chrome
5. Press Connect Wallet

**Expected behavior**
Show wallet options to connect. 

**Screenshots**
![1](https://github.com/WalletConnect/Web3ModalFlutter/assets/113566171/93a4ec8d-b41e-41ac-a8a0-0c55a9a59c71)
![2](https://github.com/WalletConnect/Web3ModalFlutter/assets/113566171/24b96078-1308-4d84-8e5e-eaf11fce5d09)
![3](https://github.com/WalletConnect/Web3ModalFlutter/assets/113566171/ff445f5e-65ff-4042-a4e0-4e49a49d7fd0)

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser: chrome
 - Version: 118.0.5993.72

**Comment by quetool** [comment]
Hello @dev-ro! Web3Modal for Flutter is not yet ready for web, we are working on it but we don't have an ETA. You can use any other option available for the web (React/Vue/Javascript) https://docs.walletconnect.com/web3modal/about
