### ISSUE TITLE
Value is not increasing

### ISSUE THREAD

**Issue by mehuldadlani** [WalletConnect/Web3ModalFlutter#42]
**Describe the bug**

**To Reproduce**
1. Go to 'HomePage'
2. Click on 'etc user send transaction'
3. Even if you change the value in eip155.dart, it is still stuck on 0.0000001 in metamask'

**Expected behavior**
It should change according to the value

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Pixel 7pro

**Additional context**

**Comment by quetool** [comment]
Hello @mehuldadlani! I honestly don't understand what you are reporting. Are you reporting an issue with the example app and not with the SDK itself?

**Comment by mehuldadlani** [comment]
Yeah like I wanted to sign a transaction but when I pass the value it is
not changing.

**Comment by mehuldadlani** [comment]
Hey any updates?

**Comment by glitch-txs** [comment]
@mehuldadlani could you share an example of what you're trying to achieve? Code snippet or a small public repo/sandbox?

**Comment by mehuldadlani** [comment]
<img width="512" alt="Screenshot 2023-10-21 at 3 49 38 AM" src="https://github.com/WalletConnect/Web3ModalFlutter/assets/90852816/5927d2c7-0054-4af4-9727-9cac518fb70f">
Here I want to send transactions on eth. This is a method in utils/eip155.dart. when I set a value to any number, it still stays as 0.0001. When it is redirected to metamask for transaction it shows 0.0001

**Comment by glitch-txs** [comment]
Check for the decimals number of the token, if it's 18 or so you'll need to parse them

**Comment by mehuldadlani** [comment]
wasn't able to understand can you give an example

**Comment by mehuldadlani** [comment]
Hey I tried parsing it but now it is showing more than 1 ETH 

  case EIP155UIMethods.ethSendTransaction:
        return ethSendTransaction(
          web3App: web3App,
          topic: topic,
          chainId: chainId,
          transaction: EthereumTransaction(
            from: address,
            to: "0xeC2265da865A947647CE6175a4a2646318f6DCEb",
            value: BigInt.from(10).pow(18).toString(),
          ),
        );
<img width="1440" alt="Screenshot 2023-10-22 at 8 52 43 PM" src="https://github.com/WalletConnect/Web3ModalFlutter/assets/90852816/f74c6b97-6a45-4b36-a8c9-af715d25b7e5">

**Comment by glitch-txs** [comment]
Check for the decimals value of the token, most are 18 but can vary

**Comment by mehuldadlani** [comment]
I got the solution umm no need

**Comment by glitch-txs** [comment]
awesome! can you share it here in case someone else face it?

**Comment by mehuldadlani** [comment]
Yeah sure!! also I was thinking, if you guys have any bounty I can rewrite you flutter docs coz there are a lot of changes needed.

**Comment by mehuldadlani** [comment]
Here for using 1 eth first convert that into gwei and now convert that gwei to hexadecimal so like for one eth value which should be entered is 0xDE0B6B3A7640000

**Comment by glitch-txs** [comment]
> if you guys have any bounty

At the moment we only have bounties for security vulnerabilities

**Comment by quetool** [comment]
Thanks @glitch-txs for taking care!

@mehuldadlani glad you solved, please bear in mind that almost everything about Web3Modal is in beta stage, documentation included as mentioned in the docs page.

**Comment by mehuldadlani** [comment]
okay sure
