### ISSUE TITLE
Can't connect to wallet

### ISSUE THREAD

**Issue by Hamza-Shewa** [WalletConnect/Web3ModalFlutter#49]
I'm using the latest stable version of Web3ModalFlutter
After connecting to a network, whenever I want to connect to wallet it returns this error

TimeoutException after 0:00:00.000000: Future not completed

and won't send the connection request to the wallet, it first happened with Metamask wallet and then I installed Trustwallet because I thought it was a problem on Metamask's end Apparently it's Flutter problem

Smartphone (please complete the following information):**
 using google pixel 7 emulator
 Android 11

**Comment by quetool** [comment]
Hello @Hamza-Shewa, not sure what you mean, would be nice to see some code to reproduce your issue or come console logs or something. The error `TimeoutException after 0:00:00.000000: Future not completed` shouldn't be related to anything in regards of connecting a wallet and you can disregard that error message (it will also be fixed in the following releases).

**Comment by Hamza-Shewa** [comment]
I'm using W3MConnectWalletButton from the package itself, and this is how I initialized my W3MService:
  ```
static W3MService w3mService = W3MService(
    projectId: 'my-project-id',
    metadata: const PairingMetadata(
      name: 'Pinky Market Place',
      description: 'Best Crypto Market Place',
      url: 'https://www.walletconnect.com/',
      icons: ['https://walletconnect.com/walletconnect-logo.png'],
    ),
  );
```
and it simple returns this error, no other information is provided:

E/flutter ( 6297): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: TimeoutException after 0:00:00.000000: Future not completed
E/flutter ( 6297): 

Thank you for your fast response

**Comment by quetool** [comment]
What version of Web3Modal are you using? Also, do you mind trying this? https://gist.github.com/quetool/f934b449ed0027f8b435622a2719328a

**Comment by Hamza-Shewa** [comment]
I'm version nu 2.0.2 
I tried the code, and it doesn't return anything and doesn't throw any exceptions, it only redirects to Metamask wallet, without showing the confirmation for connecting the wallet at all unfortunately.

**Comment by quetool** [comment]
Oh ok, I get it, please install latest beta version https://pub.dev/packages/web3modal_flutter/versions/3.0.0-beta10

It's about to get released anyway 👍

**Comment by Hamza-Shewa** [comment]
I'll test it right now, Thank you very much for your cooperation.

**Comment by Hamza-Shewa** [comment]
it returns this error:
<img width="671" alt="image" src="https://github.com/WalletConnect/Web3ModalFlutter/assets/42789638/e4848582-bb13-4eb8-a877-13b22217f431">

the initialization code is:

**Comment by quetool** [comment]
That's weird, do you mind sharing a complete example code?

**Comment by Hamza-Shewa** [comment]
here's the code, and I'm using an actual project id, just for clerification 😅
```
import 'package:flutter/material.dart';
import 'package:web3modal_flutter/web3modal_flutter.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late W3MService service;
  bool loading = true;
  @override
  void initState() {
    service = W3MService(
      projectId: 'my-project-id',
      metadata: const PairingMetadata(
        name: 'Pinky Market Place',
        description: 'Best Crypto Market Place',
        url: 'https://www.walletconnect.com/',
        icons: ['https://walletconnect.com/walletconnect-logo.png'],
      ),
    );
    initService();
    super.initState();
  }

  Future initService() async {
    await service.init();
    setState(() {
      loading = false;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            if (loading)
              const CircularProgressIndicator()
            else
              W3MConnectWalletButton(service: service),
          ],
        ),
      ),
    );
  }
}

```

**Comment by quetool** [comment]
I was able to reproduce it, taking a look right now!

**Comment by quetool** [comment]
Hello @Hamza-Shewa, the only way I can reproduce the exact same error is by passing the string `my-project-id` to the projectId parameter... 

Do you mind installing `web3modal_flutter: ^3.0.0-beta13` and set the connect button like this
```
W3MConnectWalletButton(
    service: service,
    state: ConnectButtonState.none,
),
```

If after that the W3MConnectWalletButton is disabled then your projectId is wrong.

**Comment by quetool** [comment]
Also you can see this by calling `W3MLoggerUtil.setLogLevel(W3MLogLevel.error);` before `await service.init();`

**Comment by quetool** [comment]
Hello @Hamza-Shewa, is this still an issue?

**Comment by quetool** [comment]
Feel free to reopen if still an issue.
