### ISSUE TITLE
doesn't handle multichain connection

### ISSUE THREAD

**Issue by sam-dev-1729** [WalletConnect/Web3ModalFlutter#5]
trust-wallet app support chains like [eip155:1,eip155:56,eip155:137 ,...].
why in your web3modal only could be connected with eip155:1 . 
I try to get wallets information with Cloud Explorer API but in it's response trust-wallet chains has only eip155:1 .
what can I do to handle this issue ?

**Comment by Luzzotica** [comment]
You can pass in any namespace you would like to the Web3Modal using the `setDefaultChain` method.

You can pass in multiple chains in the same namespace, as you have above.

As for why Trust only supports eip155:1, or if that is even the case, I have no idea. I would recommend you make an issue on their github or reach out to them directly. I have no direct control over them and the chains they choose to support.
