### ISSUE TITLE
[W3MService] Please provide a valid projectId. See https://docs.walletconnect.com/web3modal/flutter/options for details. 

### ISSUE THREAD

**Issue by sureshturbo** [WalletConnect/Web3ModalFlutter#59]
![281987080-7b629e77-6e81-4ce1-ad57-4f79a1e474e9](https://github.com/WalletConnect/Web3ModalFlutter/assets/44191960/21b02004-21ea-4311-934e-06766f344a2a)

flutter run --dart-define=PROJECT_ID='657cca24a6aebfa977eb5b427b87cXXX'

i put project id but it shows this error in flutter
plz help me.

**Comment by quetool** [comment]
Hello @sureshturbo, make sure you are passing a valid project id. Can you share your dApp's name?

**Comment by sureshturbo** [comment]
nft
657cca24a6aebfa977eb5b427b87c634

![image](https://github.com/WalletConnect/Web3ModalFlutter/assets/44191960/c84c27fb-556f-44ca-b9e4-992171b2e6a3)

**Comment by sureshturbo** [comment]
> Hello @sureshturbo, make sure you are passing a valid project id. Can you share your dApp's name?
nft
657cca24a6aebfa977eb5b427b87c634
![image](https://github.com/WalletConnect/Web3ModalFlutter/assets/44191960/210fef46-b2b4-4bb2-84e6-851af4413be9)

**Comment by quetool** [comment]
Thanks @sureshturbo! By the way you can confidently share your projectId, there's no harm on sharing it. In any case, I checked it and the I can run the SDK properly with your given projectId. Are you sure you are passing it right to the SDK?

**Comment by sureshturbo** [comment]
> Thanks @sureshturbo! By the way you can confidently share your projectId, there's no harm on sharing it. In any case, I checked it and the I can run the SDK properly with your given projectId. Are you sure you are passing it right to the SDK?

Sure, plz check it.

**Comment by quetool** [comment]
I mean that I already did. I already checked it and it's working fine.  Are you sure you are passing it correctly to the SDK?

**Comment by sureshturbo** [comment]
> I mean that I already did. I already checked it and it's working fine. Are you sure you are passing it correctly to the SDK?

yes, i passed correctly. can you share the your code.

**Comment by quetool** [comment]
Did you read the docs? https://docs.walletconnect.com/web3modal/flutter/options

You can also check how it's done here in the example app https://github.com/WalletConnect/Web3ModalFlutter/blob/master/example/lib/home_page.dart#L31

**Comment by sureshturbo** [comment]
> Did you read the docs? https://docs.walletconnect.com/web3modal/flutter/options
> 
> You can also check how it's done here in the example app https://github.com/WalletConnect/Web3ModalFlutter/blob/master/example/lib/home_page.dart#L31

yes, I read the docs,
and I use this repo for the testing.
![image](https://github.com/WalletConnect/Web3ModalFlutter/assets/44191960/0db90c3e-0ce6-427d-9a22-0fa68f4c9597)
I put my project id.

**Comment by quetool** [comment]
`String.fromEnvironment()` is a function that takes a key (`PROJECT_ID` in this case) to read a value from environment. https://api.flutter.dev/flutter/dart-core/String/String.fromEnvironment.html 

You shouldn't modify that file if you are going to run your project with `flutter run --dart-define=PROJECT_ID=657cca24a6aebfa977eb5b427b87c634`

Otherwise this is what you should do:

```
class DartDefines {
  static const String projectId = '657cca24a6aebfa977eb5b427b87c634';
}
```
But this 👆 solution here is kinda pointless.

**Comment by quetool** [comment]
And, as the documentation says, if you want to "hardcode" your projectId you do so in the service instance
https://docs.walletconnect.com/web3modal/flutter/options

**Comment by sureshturbo** [comment]
> And, as the documentation says, if you want to "hardcode" your projectId you do so in the service instance https://docs.walletconnect.com/web3modal/flutter/options
> 
> So basically this
> 
> ```
> final _w3mService = W3MService(
>   projectId: '657cca24a6aebfa977eb5b427b87c634',
>   metadata: const PairingMetadata(
>     name: 'Web3Modal Flutter Example',
>     description: 'Web3Modal Flutter Example',
>     url: 'https://www.walletconnect.com/',
>     icons: ['https://walletconnect.com/walletconnect-logo.png'],
>     redirect: Redirect(
>       native: 'flutterdapp://',
>       universal: 'https://www.walletconnect.com',
>     ),
>   ),
> );
> await _w3mService.init();
> ```

Okay, I tried this code. but it give the null error,
 I have no idea Plz correct me.
 ****

**Comment by quetool** [comment]
Can you share YOUR implementation?

**Comment by sureshturbo** [comment]
> > And, as the documentation says, if you want to "hardcode" your projectId you do so in the service instance https://docs.walletconnect.com/web3modal/flutter/options
> > So basically this
> > ```
> > final _w3mService = W3MService(
> >   projectId: '657cca24a6aebfa977eb5b427b87c634',
> >   metadata: const PairingMetadata(
> >     name: 'Web3Modal Flutter Example',
> >     description: 'Web3Modal Flutter Example',
> >     url: 'https://www.walletconnect.com/',
> >     icons: ['https://walletconnect.com/walletconnect-logo.png'],
> >     redirect: Redirect(
> >       native: 'flutterdapp://',
> >       universal: 'https://www.walletconnect.com',
> >     ),
> >   ),
> > );
> > await _w3mService.init();
> > ```
> 
> Okay, I tried the code , it is working fine, Thank so much for the support

the example repo is working fine,
I create the new project for the testing I import all the necessary things like 
1. AndroidManifest.xml add queries
2. add the flutter pub add web3modal_flutter dependencies

but I have PairingMetadata as an error 
I want to know about new project integration
please correct me.
https://github.com/sureshturbo/nft.git

**Comment by quetool** [comment]
I don't see you have web3modal dependency installed in your project https://github.com/sureshturbo/nft/blob/master/pubspec.yaml

**Comment by sureshturbo** [comment]
> I don't see you have web3modal dependency installed in your project https://github.com/sureshturbo/nft/blob/master/pubspec.yaml

yes, actually i have some version issue , so now I add the dependency without version plz check
