### ISSUE TITLE
Web Platform support

### ISSUE THREAD

**Issue by nuzhata** [WalletConnect/Web3ModalFlutter#69]
Please add web support for this project :)

**Comment by ianwhite2** [comment]
any update on web support , I can see the PR but it is WIP can some one tell us the estimate or alternative

**Comment by quetool** [comment]
Hello! Yes indeed Web Support is still a WIP. Unfortunately I don't have a real ETA but our goal is to ship it during this first quarter of the year. We first need to support web on our Core SDK (https://github.com/WalletConnect/WalletConnectFlutterV2) and that is pretty much done. Then we can focus on Web3Modal!

I get that probably you would want to have one codebase for all of your platforms (Flutter hu? 💙) but for the time being our Web3Modal WEB repo is your best option https://github.com/WalletConnect/web3modal

You can choose either React, Vue, Next or JS https://docs.walletconnect.com/web3modal/about
Thanks for your patience!

**Comment by ianwhite2** [comment]
@quetool - Alright ,Are there any alternative for me then My requirement is straightforward  where I want to connect to metamask and couple of other wallets connect to it, show the address and sign the transaction and send the transaction. Can I use https://github.com/WalletConnect/WalletConnectFlutterV2 for this I can see there is a example inside WalletConnectFlutterV2 with web Suport but some how not able to connect metamask in it

**Comment by ianwhite2** [comment]
Ah no My question here was  "I'm currently developing a project using Flutter and need to ensure compatibility with both web and mobile platforms. I don't want to delay until the first quarter of 2024. I've noticed that WalletConnectModalFlutter also supports web applications, in addition to mobile. This seems like it could facilitate wallet connections and transactions for my project. Can you confirm if my understanding is correct?

**Comment by quetool** [comment]
Hello @ianwhite2! `WalletConnectModalFlutter` also relies on `WalletConnectFlutterV2` under the hood so it shouldn't support web in a full way either. However I agree it might be easier to try that out for the time being.

**Comment by ianwhite2** [comment]
@quetool  - I've noticed that the `WalletConnectModalFlutter` example application functions correctly in Chrome, which leads me to believe that it should also operate effectively in a broader web context. However, I'm wondering if there might be any particular aspects or requirements in the web environment that could potentially hinder the library's functionality. Could there be elements I'm overlooking that would indicate the library is not compatible with web platforms? , Please let me know

**Comment by gvaidyayolo** [comment]
@quetool  - can you please check my above comment

**Comment by ianwhite2** [comment]
@quetool - any updated on the above comment , why you are saying that it doesn't support the web ?

**Comment by quetool** [comment]
Hello @ianwhite2! What I'm trying to say is that, given the fact that `WalletConnectModalFlutter` depends from `WalletConnectFlutterV2`, which is not yet entirely refactored to support web, then `WalletConnectModalFlutter` shouldn't fully support on web either. Flutter's SDKs were born initially just for mobile, and we are now working on support web as well. Furthermore, I see `WalletConnectModalFlutter` depends from `appcheck`, which is a mobile only package, so a bit of work must be done, on every Flutter SDK to fully support web.

You can go ahead an try to run `WalletConnectModalFlutter` on web, it will probably run "just fine", however, bear in mind that we are not currently guaranteeing and smooth behavior on Web on either of our Flutter SDKs.

**Comment by ianwhite2** [comment]
@quetool  - Thanks

**Comment by crypblizz8** [comment]
Can we close this @quetool ?

**Comment by rollchad** [comment]
@crypblizz8 @quetool does web platform work now? Getting this error

```
│ ⛔ [ExplorerService] Error fetch wallets params: {page: 1, entries: 48, platform: platformtype.desktop}
```

![image](https://github.com/WalletConnect/Web3ModalFlutter/assets/138987133/55f2143a-40eb-4320-897d-1b350814df80)

**Comment by quetool** [comment]
Hello @rollchad! Not sure why the reason is "completed", might be a default option when closing but Web support is not yet done.

**Comment by quetool** [comment]
Nor desktop fwiw

**Comment by rollchad** [comment]
Gotcha. The web3 world is sleeping on mobile due to lack of web support from Flutter tooling. I can't describe how big this library will become if you are the first to ship web support. Keep going.

**Comment by ygoncharenkofwd** [comment]
@quetool can you please describe the current status of the Flutter Web support implementation? What is done and what has to be done now? Can I help you anyhow?

I'm very interested in having it available ASAP, if you can share some checklist and the details maybe the community can help you.

**Comment by quetool** [comment]
Hello @ygoncharenkofwd! Thanks for reaching out! Since **Web3ModalFlutter** heavily depends on [WalletConnectFlutterV2](https://github.com/WalletConnect/WalletConnectFlutterV2) then **WalletConnectFlutterV2** has to support web platform (the work there is almost done, further testing has to be made). After that, it's a matter of running Web3ModalFlutter on web platform and check which dependencies has to be substituted/removed if they don't support web and/or implement conditional imports. Web3Modal was not intended to be web platform compatible, since we already have great web SDKs for that, so now the work towards web support for Flutter SDKs is sensitive because we don't obviously want to break anything. I'll try to make some time during the following weeks for this!

**Comment by kaumudpa** [comment]
+1

**Comment by redDwarf03** [comment]
i try to help on this subject: https://github.com/WalletConnect/Web3ModalFlutter/issues/108
