### ISSUE TITLE
Example app, `_fetchNativeAppData()` error when performing GET request

### ISSUE THREAD

**Issue by GangemiLorenzo** [WalletConnect/Web3ModalFlutter#70]
**Describe the bug**
I'm trying to run the example application within the project.
I've cloned the repo, run `flutter pub get` and read the instructions in the `README.md` file inside the example folder.

When I run the example project, the `_fetchNativeAppData()` method from `explorer_service.dart` is called.
It successfully retrieves `headers`, the `uri` and proceed with the GET request to the endpoint.

The request does not fail, but it simply returns "Forbidden" string.

This seems to cause the json decode to fail and crash with this log:

```
I/flutter (29476): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (29476): │ FormatException: Unexpected character (at character 1)
I/flutter (29476): │ Forbidden
I/flutter (29476): │ ^
I/flutter (29476): │ 
I/flutter (29476): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (29476): │ #0   _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383:5)
I/flutter (29476): │ #1   _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1250:9)
I/flutter (29476): │ #2   _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:915:22)
I/flutter (29476): │ #3   _parseJson (dart:convert-patch/convert_patch.dart:35:10)
I/flutter (29476): │ #4   JsonDecoder.convert (dart:convert/json.dart:610:36)
I/flutter (29476): │ #5   JsonCodec.decode (dart:convert/json.dart:216:41)
I/flutter (29476): │ #6   jsonDecode (dart:convert/json.dart:155:10)
I/flutter (29476): │ #7   ExplorerService._fetchNativeAppData (package:web3modal_flutter/services/explorer_service/explorer_service.dart:164:9)
I/flutter (29476): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (29476): │ ⛔ [ExplorerService] Error fetching native apps data
I/flutter (29476): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

I read about a similar issue [here](https://github.com/WalletConnect/Web3ModalFlutter/issues/68).
I still opened this since it seems to be a different problem.

**To Reproduce**
Simply move into the `example` folder and run:
`flutter run --dart-define=PROJECT_ID={PROJECT_ID}`

**Expected behavior**
I would expect the endpoint to return the data, or the app to handle the error.
But of course I understand this is just an example app.
I'm just looking to run the app.

**Smartphone:**
 - Device: Oneplus 6T

**Comment by GangemiLorenzo** [comment]
> Hello, @GangemiLorenzo ! Couple of questions:
> 
> * Are you in any OFAC-restricted country? [_fetchNativeAppData get uri Failed #68 (comment)](https://github.com/WalletConnect/Web3ModalFlutter/issues/68#issuecomment-1832440956)
> * Are you passing a valid `projectId`?

Hello @quetool 
No I'm not in any OFAC-restricted country, I'm running the code from Italy.
The projectId is passing the regex check but it's totally random.

Should it be registered or created somewhere?

**Comment by quetool** [comment]
Yes, you can find a "Don't have a Project ID?" banner on the docs in order to create a valid project: https://docs.walletconnect.com/web3modal/flutter/options

**Comment by GangemiLorenzo** [comment]
Oh sorry, the banner is giant and I still missed it ahaha

Thanks a lot for the support and sorry for the inconvenience
