### ISSUE TITLE
Executing a transaction with web3modal_flutter doesn't popup the wallet for transaction confirmation automatically.

### ISSUE THREAD

**Issue by AbdulRafaySiddiqui** [WalletConnect/Web3ModalFlutter#74]
**Describe the bug**
When using web3modal_flutter, the app connects to the wallet without issues. However, when attempting to execute a transaction, it fails to automatically prompt the wallet (tested with Metamask and Trust Wallet) interface for transaction confirmation. Instead, the transaction confirmation modal only appears in Metamask when manually navigating back to the wallet app from my application.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the app and connect to the wallet using web3modal_flutter.
2. Attempt to initiate a transaction.
3. Observe that the Metamask or Trust Wallet interface does not automatically pop up for transaction confirmation.
4. Manually navigate back to the Metamask app and notice the transaction confirmation modal is present.

**Expected behaviour**
I expected the Metamask or Trust Wallet interface to automatically pop up for transaction confirmation when a transaction is initiated from the app.

**Smartphone (please complete the following information):**
 - Device: One Plus 7T Pro
 - OS: Android 12
 - Browser: Oxygen OS
 - Version: 12.1

**Comment by quetool** [comment]
Hello @AbdulRafaySiddiqui, immediately after sending the Sign request you should open the Connected Wallet by calling `launchConnectedWallet();` 

See https://docs.walletconnect.com/web3modal/flutter/actions#launch-the-current-wallet
