### ISSUE TITLE
WalletConnect V2 Migration

### ISSUE THREAD

**Issue by rennylangat** [WalletConnect/Web3ModalFlutter#8]
The depreciation of V1 on 28th has rendered lots of dApps useless and their users are complaining. Is there a way that we devs can contribute towards the migration in order to hasten this process? This is a package by us for us therefore the faster we get it up and running the faster the products are back in business

**Comment by Luzzotica** [comment]
Work is being on the WalletConnectModal repo to make it easy to swap over from V1.

I'll be building a migration guide over the next few days.

If you want to help, or have additional issues, the best place to put them is over in the WalletConnectModal repo, which can be found in the readme of this repo.
