### ISSUE TITLE
Multi wallet connection and switching the selected wallet 

### ISSUE THREAD

**Issue by faaqi** [WalletConnect/Web3ModalFlutter#83]
I wanna inquire if this package supports multi wallet connection and user can switch between wallets in the app.

**Comment by quetool** [comment]
Hello @faaqi! Nope it does not support it yet.

**Comment by faaqi** [comment]
Hi @quetool

Got it. 

I'm checking this again to see if there is any update in terms of the multi wallet connection? 

Like for now we're handling the connections manually using wallet connect package. Can u recommend some approaches we can do to use wallet modal as well wrt multi wallet connection?

"Ability to change account is up to the wallet."

I didn't get it. Can u explain

**Comment by quetool** [comment]
I mean that walletconnect protocol works always with the current active account in the wallet (like any other protocol). Switching between accounts (what you call wallets) during sign requests or even session proposals it's up to the Wallet app to allow that. For instance, I know Zerion allows that (and probably some other wallet apps as well)

**Comment by faaqi** [comment]
Thanks. @quetool 

I know that it's upto the wallet. Can u confirm 1 thing that does this package supports that process? or will it in the future? to show all connected wallets with their respective balances.

 Mean to say that user can see all the wallets with the balances and switching to other wallet should not re-initiate the connection. Multiple connections need to be maintained (which we're doing manually)

I guess we just need to diplay the modal on connect wallet button and thats it. 
 
<img width="341" alt="image" src="https://github.com/WalletConnect/Web3ModalFlutter/assets/61233208/a65fa4af-8c54-4e63-bbb2-38bdd26ded53">

**Comment by Sam-Newman** [comment]
Hey @faaqi !

Thanks for reaching out. I just want to confirm we are using the same terminology here. 

Wallets = Wallet providers (metamask, TrustWallet etc)
Accounts = EOA addresses 
(you may have multiple accounts in one wallet)

We are soon to be working on features for users to be able to connect multiple accounts, view balances accross the accounts and to seamless switch accounts. 

Regarding connecting multiple Wallets, for example connecting Metamask and TrustWallet at the same time, this is something we do not currently have on our roadmap but could look into it if there is demand. 

Please can you confirm which use case you need?

**Comment by faaqi** [comment]
Oh okay. @Sam-Newman 

We need to handle multiple wallets ( like MM, Trust wallet) and maintain them connected at same time so user can switch between them seamlessly. The External app will only trigger for signing transactions.

**Comment by Sam-Newman** [comment]
Thanks for confirming. I have also heard this from others so it's something we will add to the roadmap. 

Keep an eye out for updates, would be great to have you as a alpha tester & launch partner if you are up for that?

**Comment by faaqi** [comment]
It would be great for me to be an alpha tester. Just opening this issue again to get your response on multi wallets connection feature. @Sam-Newman

**Comment by Sam-Newman** [comment]
Hey @faaqi Thanks for reaching out again. I cannot give you any updates on the timeline for this yet. It's on our backlog but we have not scheduled the work. I will keep you updated when I know more.
