### ISSUE TITLE
Error: Type 'EventArgs' not found. with web3modal_flutter: ^3.1.0

### ISSUE THREAD

**Issue by DhavalRKansara** [WalletConnect/Web3ModalFlutter#88]
Getting below issue while using web3modal_flutter: ^3.1.0 in my Project.

Could not build the precompiled application for the device.

Error (Xcode): ../../../.pub-cache/hosted/pub.dev/web3modal_flutter-3.1.0/lib/services/w3m_service/i_w3m_service.dart:22:35: Error: Type 'EventArgs' not found.

**Comment by quetool** [comment]
Hello @DhavalRKansara! Do you have any more information? I tried to reproduce this and I wasn't able. 
Do you mind trying the following?
1. Create a new flutter project
2. Add `web3modal_flutter: ^3.1.0` in dependencies
3. Locate your Podfile under `/ios/Podfile` and add the following as the first line: `platform :ios, '13.0'`
4. Navigate to `ios` folder in your terminal (`cd ios`)  and run `pod install`
5. Run your project


Let me know how it goes.
