### ISSUE TITLE
How can I check selected wallet of user after connecting

### ISSUE THREAD

**Issue by Mash-Woo** [WalletConnect/Web3ModalFlutter#89]
After connecting, I want to check the user's current connected wallet.

Web3modal can't send transactions with Metamask, so I want to check what the user's connected wallet is. I can throw them an alert dialogue if it's a meta mask. We still do not support this function.

**Comment by quetool** [comment]
Hello @Mash-Woo What do you mean? I use MetaMask regularly with Web3Modal as a lot of other people do as well

**Comment by Mash-Woo** [comment]
> Hello @Mash-Woo What do you mean? I use MetaMask regularly with Web3Modal as a lot of other people do as well

I am facing the same problem with Metamask with this issue although I am using web3modal

https://github.com/WalletConnect/WalletConnectFlutterV2/issues/176

**Comment by Mash-Woo** [comment]
@quetool Do you have any solutions for this

**Comment by quetool** [comment]
In order to get to know the connected wallet, you can check the `SessionData` object after connection. `sessionData.peer.metadata.name` would be the name of the connected wallet.

**Comment by Mash-Woo** [comment]
Yes, thank you

**Comment by Mash-Woo** [comment]
This has been solved. @quetool You can close this
