### ISSUE TITLE
smart contract interaction getting issue 

### ISSUE THREAD

**Issue by SevenBitsRashmi** [WalletConnect/Web3ModalFlutter#9]
Reference link used this https://github.com/WalletConnect/Web3ModalFlutter/issues/6 

After clicking on confirm button getting below message

result = {_Map} size = 4
 0 = {map entry} "code" -> 4001
 1 = {map entry} "line" -> 64
 2 = {map entry} "column" -> 331
 3 = {map entry} "sourceURL" -> "index.android.bundle"

**Comment by Luzzotica** [comment]
This repo is deprecated.

Please recreate this issue (With perhaps more info) in the WalletConnectModal repo.
