### ISSUE TITLE
How to access connectResponse in the latest release 3.1.0?

### ISSUE THREAD

**Issue by DhavalRKansara** [WalletConnect/Web3ModalFlutter#91]
Hi Team, 

I have upgraded the package to the latest release 3.1.0 where I found we removed the public parameter `connectResponse` and we have done other changes as well...

I found we do assign the value to `connectResponse` in the `buildConnectionUri` and then we are calling `_awaitConnectionCallback` method but over here we are not storing the 'await connectResponse.session.future` anywhere which is needed to me. If we done changes related to to `_currentSession` then we should assign the value to it in the `_awaitConnectionCallback`. 

I am stuck here in the production release please let me know the solution for the same using which I can fix the issues.

**Comment by quetool** [comment]
Hello @DhavalRKansara, I don't understand your issue, could you elaborate a bit more, maybe with some reproducible code? I understand that you were using the `connectResponse` parameter which is not available anymore but that parameter has no point to be public. What do you need to do exactly?

**Comment by DhavalRKansara** [comment]
Hi @quetool  I do use the `connectResponse` parameter earlier as show below in code sample. Could you please guide me how I can replace it with latest changes? 

     ```
     SessionData?  session =
        await (await service).connectResponse?.session.future.timeout(
                 _mediumRequestWaitingTime,
                 onTimeout: () => throw TimeoutException('Timed out'),
          );
```

**Comment by DhavalRKansara** [comment]
Hi @quetool I need a SessionData which we go in the response of `_web3App!.connect` sharing the ss of code below from version 3.0.1. 

As per the latest update, the `connectResponse` is not available to access directly How can I get the session data, which stores the result of `_web3App!.connect`?

<img width="645" alt="Screenshot 2024-02-02 at 8 03 15 PM" src="https://github.com/WalletConnect/Web3ModalFlutter/assets/44993081/41db3334-f9d7-4b5a-a79e-066a82e96c23">

**Comment by quetool** [comment]
Oh I get it now. Simply, you just use `w3mService.session?.sessionData`

**Comment by DhavalRKansara** [comment]
> Oh I get it now. Simply, you just use `w3mService.session?.sessionData`

Yes, But where are you assing the the `_web3App!.connect` to `session.sessionData`?

**Comment by quetool** [comment]
You can also subscribe to `w3mService.onSessionConnectEvent` like this:

```dart
_w3mService.onSessionConnectEvent.subscribe(_onSessionConnect);

void _onSessionConnect(SessionConnect? args) {
  // args?.session is what you are looking for
}
```

This will be triggered once you approve the connection on your wallet.

**Comment by quetool** [comment]
Have you checked the example app in the repo?

**Comment by DhavalRKansara** [comment]
> Oh I get it now. Simply, you just use `w3mService.session?.sessionData`

Does this will return the same object which we do get from `connectResponse?.session`?

**Comment by quetool** [comment]
Yes!

**Comment by crypblizz8** [comment]
Need any more help @DhavalRKansara ?

**Comment by quetool** [comment]
Closing for now. Feel free to re-open if needed!
