### ISSUE TITLE
Lost SharedPreference data when disconnected from wallet

### ISSUE THREAD

**Issue by TGVRock** [WalletConnect/Web3ModalFlutter#92]
**Describe the bug**
When I disconnect from the wallet, the data stored in SharedPreference is lost.
Can you please consider making it so that the data is not lost even if the session with the wallet is disconnected?

**To Reproduce**
1. Use the example app in the repository.
2. Modify the _MyHomePageState class as follows:
```diff
--- a/example/lib/home_page.dart
+++ b/example/lib/home_page.dart
@@ -1,3 +1,5 @@
+import 'dart:async';
+
 import 'package:flutter/material.dart';

 import 'package:web3modal_flutter/web3modal_flutter.dart';
@@ -22,10 +24,26 @@ class MyHomePage extends StatefulWidget {
 class _MyHomePageState extends State<MyHomePage> {
   late W3MService _w3mService;

+  String _sp = "";
+
+  // Retrieve data from SharedPreference
+  Future<void> reloadPreference(Timer timer) async {
+    final SharedPreferences prefs = await SharedPreferences.getInstance();
+    setState(() {
+      _sp = prefs.getString('preference_test') ?? 'key not found.';
+    });
+  }
+
   @override
   void initState() {
     super.initState();
     _initializeService();
+    // Periodically retrieve data from SharedPreference.
+    Timer.periodic(const Duration(seconds: 3), reloadPreference);
+    // Save data in SharedPreference only once at initialization
+    SharedPreferences.getInstance().then((prefs) {
+      prefs.setString('preference_test', 'value saved');
+    });
   }

   void _initializeService() async {
@@ -141,6 +159,7 @@ class _MyHomePageState extends State<MyHomePage> {
                 color: Web3ModalTheme.colorsOf(context).foreground100,
               ),
             ),
+            Text(_sp),
             _ButtonsView(w3mService: _w3mService),
             const Divider(height: 0.0, color: Colors.transparent),
             _ConnectedView(w3mService: _w3mService)
```
3. Build & run.
4. After confirming that the `value saved` text appears above the `Select network` button, click the `Select network` button.
5. Select a network wallet and connect to the wallet.
6. After returning to the example app, click the `Disconnect` button.
7. The data saved in SharedPreference will disappear and the text above the `Select network` button will change to `key not found.`.

**Expected behavior**
The data stored in SharedPreference should not disappear even after the wallet is disconnected.

**Desktop (please complete the following information):**
Unconfirmed

**Smartphone (please complete the following information):**
 - Device: FCG01
 - OS: Android13

**Comment by quetool** [comment]
Hello @TGVRock! This is indeed a very good point! I'll try to prepare a fix ASAP! Thanks!

**Comment by quetool** [comment]
To be clear, the bug here is that our calling for clearing our shared preferences it is clearing also your host app's shared preferences, which it shouldn't. (Our shared preferences must be still cleared upon disconnection)

**Comment by TGVRock** [comment]
Thank you for addressing the issue!
Best regards.

**Comment by quetool** [comment]
Hello @TGVRock! This fix has been included in latest beta version. Please check! https://pub.dev/packages/web3modal_flutter/versions/3.1.1-beta02/changelog

Thanks for reporting it!
